(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-11 17:00:24.507469'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-11 17:00:24.507469')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
Exception while resolving variable 'form' in template 'register.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}, {'has_account': True}]"
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-11 17:05:16.732225'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-11 17:05:16.732225')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
Exception while resolving variable 'form' in template 'register.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}, {'has_account': True}]"
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = newConsommateursForm()
NameError: global name 'newConsommateursForm' is not defined
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 12, in __init__
    forms.TextField(
AttributeError: 'module' object has no attribute 'TextField'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 17, in __init__
    validators.isAlphaNumeric,
AttributeError: 'module' object has no attribute 'isAlphaNumeric'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 19, in __init__
    self.isValidUsername]
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 227, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'validator_list'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 18, in __init__
    self.isValidUsername]
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 227, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'validator_list'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 16, in __init__
    is_required=True,
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 227, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'length'
(0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 17, in __init__
    is_required=True,
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 227, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'is_required'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 16, in __init__
    maxlength=30,
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 227, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'field_name'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 81, in register
    form = forms.FormWrapper(manipulator, new_data, errors)
NameError: global name 'forms' is not defined
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 82, in register
    form = forms.FormWrapper(manipulator, new_data, errors)
AttributeError: 'module' object has no attribute 'FormWrapper'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Forbidden (CSRF token missing or incorrect.): /consommateurs/register
Forbidden (CSRF token missing or incorrect.): /consommateurs/register
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Forbidden (CSRF token missing or incorrect.): /consommateurs/register
