(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-11 17:00:24.507469'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-11 17:00:24.507469')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
Exception while resolving variable 'form' in template 'register.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}, {'has_account': True}]"
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-11 17:05:16.732225'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-11 17:05:16.732225')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
Exception while resolving variable 'form' in template 'register.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}, {'has_account': True}]"
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = newConsommateursForm()
NameError: global name 'newConsommateursForm' is not defined
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 12, in __init__
    forms.TextField(
AttributeError: 'module' object has no attribute 'TextField'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 17, in __init__
    validators.isAlphaNumeric,
AttributeError: 'module' object has no attribute 'isAlphaNumeric'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 19, in __init__
    self.isValidUsername]
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 227, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'validator_list'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 18, in __init__
    self.isValidUsername]
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 227, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'validator_list'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 16, in __init__
    is_required=True,
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 227, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'length'
(0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 17, in __init__
    is_required=True,
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 227, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'is_required'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 43, in register
    manipulator = NewConsommateursForm()
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/forms.py", line 16, in __init__
    maxlength=30,
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 227, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'field_name'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 81, in register
    form = forms.FormWrapper(manipulator, new_data, errors)
NameError: global name 'forms' is not defined
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/register
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 82, in register
    form = forms.FormWrapper(manipulator, new_data, errors)
AttributeError: 'module' object has no attribute 'FormWrapper'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Forbidden (CSRF token missing or incorrect.): /consommateurs/register
Forbidden (CSRF token missing or incorrect.): /consommateurs/register
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Forbidden (CSRF token missing or incorrect.): /consommateurs/register
(0.014) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Not Found: /consommateurs/accounts
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Not Found: /consommateurs/accounts/register
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/accounts/register/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: registration/registration_form.html
Not Found: /consommateurs/accounts/register/toto
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: registration/registration_form.html
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: registration/registration_form.html
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Internal Server Error: /consommateurs/new
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 30, in new
    form = UsersForm(request.POST)
NameError: global name 'UsersForm' is not defined
Internal Server Error: /consommateurs/new
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/views.py", line 30, in new
    form = UsersForm(request.POST)
NameError: global name 'UsersForm' is not defined
(0.001) SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."username" = 'jadjay666' LIMIT 1; args=(u'jadjay666',)
(0.000) SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."username" = 'jadjay666' LIMIT 1; args=(u'jadjay666',)
(0.000) BEGIN; args=None
(0.001) INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$24000$yXpZAbOJMuK1$sHUgnovP5OiZ7kj8LZ8G82DZMHx332/wAiYJXzPDJuQ=', NULL, 0, 'jadjay666', '', '', 'jadjay+666@rachetjay.fr', 0, 0, '2016-01-12 09:41:02.371952'); args=[u'pbkdf2_sha256$24000$yXpZAbOJMuK1$sHUgnovP5OiZ7kj8LZ8G82DZMHx332/wAiYJXzPDJuQ=', None, False, u'jadjay666', u'', u'', u'jadjay+666@rachetjay.fr', False, False, u'2016-01-12 09:41:02.371952']
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/registration/views.py", line 33, in dispatch
    return super(RegistrationView, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 222, in post
    return self.form_valid(form)
  File "/usr/local/lib/python2.7/dist-packages/registration/views.py", line 36, in form_valid
    new_user = self.register(form)
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/views.py", line 36, in register
    new_user = self.create_inactive_user(form)
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/views.py", line 55, in create_inactive_user
    self.send_activation_email(new_user)
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/views.py", line 89, in send_activation_email
    context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: registration/activation_email_subject.txt
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."username" = 'jadjay666' LIMIT 1; args=(u'jadjay666',)
(0.001) SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."username" = 'jadjay667' LIMIT 1; args=(u'jadjay667',)
(0.000) BEGIN; args=None
(0.000) INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$24000$HpOpNQzfjrRg$iwp4/bl6kmpsGaXXjS6xKvOBzAyvdSNGskAEqNHYxTg=', NULL, 0, 'jadjay667', '', '', 'jadjay+667@rachetjay.fr', 0, 0, '2016-01-12 09:42:44.205375'); args=[u'pbkdf2_sha256$24000$HpOpNQzfjrRg$iwp4/bl6kmpsGaXXjS6xKvOBzAyvdSNGskAEqNHYxTg=', None, False, u'jadjay667', u'', u'', u'jadjay+667@rachetjay.fr', False, False, u'2016-01-12 09:42:44.205375']
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/registration/views.py", line 33, in dispatch
    return super(RegistrationView, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 222, in post
    return self.form_valid(form)
  File "/usr/local/lib/python2.7/dist-packages/registration/views.py", line 36, in form_valid
    new_user = self.register(form)
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/views.py", line 36, in register
    new_user = self.create_inactive_user(form)
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/views.py", line 55, in create_inactive_user
    self.send_activation_email(new_user)
  File "/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/views.py", line 94, in send_activation_email
    context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: registration/activation_email.txt
(0.000) SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."username" = 'jadjay667' LIMIT 1; args=(u'jadjay667',)
(0.001) SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."username" = 'jadjay668' LIMIT 1; args=(u'jadjay668',)
(0.000) BEGIN; args=None
(0.000) INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES ('pbkdf2_sha256$24000$JmMCQWPLZo2U$/XSMv4d5bzW30qIkorGHu8Kqm+vyDTjwDBWOHem5qkM=', NULL, 0, 'jadjay668', '', '', 'jadjay+668@rachetjay.fr', 0, 0, '2016-01-12 09:45:15.397368'); args=[u'pbkdf2_sha256$24000$JmMCQWPLZo2U$/XSMv4d5bzW30qIkorGHu8Kqm+vyDTjwDBWOHem5qkM=', None, False, u'jadjay668', u'', u'', u'jadjay+668@rachetjay.fr', False, False, u'2016-01-12 09:45:15.397368']
Internal Server Error: /accounts/register/complete/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: registration/registration_complete.html
Not Found: /accounts/
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Not Found: /accounts/login
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 82, in resolve_template
    return get_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: registration/login.html
Not Found: /accounts/
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Not Found: /accounts/activate/ImphZGpheTY2OCI:1aIvVr:KDp3CTa1MnIPVNqLM9a-csWhd9Y
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
(0.001) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE ("auth_user"."username" = 'jadjay668' AND "auth_user"."is_active" = 0); args=(u'jadjay668', False)
(0.000) BEGIN; args=None
(0.000) UPDATE "auth_user" SET "password" = 'pbkdf2_sha256$24000$JmMCQWPLZo2U$/XSMv4d5bzW30qIkorGHu8Kqm+vyDTjwDBWOHem5qkM=', "last_login" = NULL, "is_superuser" = 0, "username" = 'jadjay668', "first_name" = '', "last_name" = '', "email" = 'jadjay+668@rachetjay.fr', "is_staff" = 0, "is_active" = 1, "date_joined" = '2016-01-12 09:45:15.397368' WHERE "auth_user"."id" = 5; args=(u'pbkdf2_sha256$24000$JmMCQWPLZo2U$/XSMv4d5bzW30qIkorGHu8Kqm+vyDTjwDBWOHem5qkM=', False, u'jadjay668', u'', u'', u'jadjay+668@rachetjay.fr', False, True, u'2016-01-12 09:45:15.397368', 5)
Internal Server Error: /accounts/activate/complete/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 74, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: registration/activation_complete.html
Not Found: /admin
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'registration.backends.hmac.urls' from '/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/urls.pyc'> (None:None) ^accounts/>"
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-12 09:49:25.291121'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-12 09:49:25.291121')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f54181c8410>>, 'user': <SimpleLazyObject: <User: admin>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f54180560d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f5413591fd0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': <django.utils.functional.__proxy__ object at 0x7f5419d24590>, 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056610>, 'add_url': u'/admin/auth/group/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056750>, 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x7f5419cad310>, 'app_label': 'auth'}, {'app_url': u'/admin/boissons/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/boissons/', 'object_name': 'boissons', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056510>, 'add_url': u'/admin/boissons/boissons/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/stock/', 'object_name': 'Stock', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056410>, 'add_url': u'/admin/boissons/stock/add/'}], 'has_module_perms': True, 'name': u'Boissons', 'app_label': u'boissons'}, {'app_url': u'/admin/consommateurs/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommateurs/', 'object_name': 'consommateurs', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056690>, 'add_url': u'/admin/consommateurs/consommateurs/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommation/', 'object_name': 'consommation', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056890>, 'add_url': u'/admin/consommateurs/consommation/add/'}], 'has_module_perms': True, 'name': u'Consommateurs', 'app_label': u'consommateurs'}], 'site_title': <django.utils.functional.__proxy__ object at 0x7f5419d24550>, 'title': <django.utils.functional.__proxy__ object at 0x7f5419d245d0>, 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': <django.utils.functional.__proxy__ object at 0x7f5413591410>, 'add_url': u'/admin/auth/group/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': <django.utils.functional.__proxy__ object at 0x7f54135912d0>, 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x7f5419cad310>, 'app_label': 'auth'}, {'app_url': u'/admin/boissons/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/boissons/', 'object_name': 'boissons', 'name': <django.utils.functional.__proxy__ object at 0x7f54135911d0>, 'add_url': u'/admin/boissons/boissons/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/stock/', 'object_name': 'Stock', 'name': <django.utils.functional.__proxy__ object at 0x7f54180565d0>, 'add_url': u'/admin/boissons/stock/add/'}], 'has_module_perms': True, 'name': u'Boissons', 'app_label': u'boissons'}, {'app_url': u'/admin/consommateurs/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommateurs/', 'object_name': 'consommateurs', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056150>, 'add_url': u'/admin/consommateurs/consommateurs/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommation/', 'object_name': 'consommation', 'name': <django.utils.functional.__proxy__ object at 0x7f54135918d0>, 'add_url': u'/admin/consommateurs/consommation/add/'}], 'has_module_perms': True, 'name': u'Consommateurs', 'app_label': u'consommateurs'}], u'LANGUAGE_CODE': 'fr-fr', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f54181c8410>>, 'user': <SimpleLazyObject: <User: admin>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f54180560d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f5413591fd0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': <django.utils.functional.__proxy__ object at 0x7f5419d24590>, 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056610>, 'add_url': u'/admin/auth/group/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056750>, 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x7f5419cad310>, 'app_label': 'auth'}, {'app_url': u'/admin/boissons/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/boissons/', 'object_name': 'boissons', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056510>, 'add_url': u'/admin/boissons/boissons/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/stock/', 'object_name': 'Stock', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056410>, 'add_url': u'/admin/boissons/stock/add/'}], 'has_module_perms': True, 'name': u'Boissons', 'app_label': u'boissons'}, {'app_url': u'/admin/consommateurs/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommateurs/', 'object_name': 'consommateurs', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056690>, 'add_url': u'/admin/consommateurs/consommateurs/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommation/', 'object_name': 'consommation', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056890>, 'add_url': u'/admin/consommateurs/consommation/add/'}], 'has_module_perms': True, 'name': u'Consommateurs', 'app_label': u'consommateurs'}], 'site_title': <django.utils.functional.__proxy__ object at 0x7f5419d24550>, 'title': <django.utils.functional.__proxy__ object at 0x7f5419d245d0>, 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': <django.utils.functional.__proxy__ object at 0x7f5413591410>, 'add_url': u'/admin/auth/group/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': <django.utils.functional.__proxy__ object at 0x7f54135912d0>, 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x7f5419cad310>, 'app_label': 'auth'}, {'app_url': u'/admin/boissons/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/boissons/', 'object_name': 'boissons', 'name': <django.utils.functional.__proxy__ object at 0x7f54135911d0>, 'add_url': u'/admin/boissons/boissons/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/stock/', 'object_name': 'Stock', 'name': <django.utils.functional.__proxy__ object at 0x7f54180565d0>, 'add_url': u'/admin/boissons/stock/add/'}], 'has_module_perms': True, 'name': u'Boissons', 'app_label': u'boissons'}, {'app_url': u'/admin/consommateurs/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommateurs/', 'object_name': 'consommateurs', 'name': <django.utils.functional.__proxy__ object at 0x7f5418056150>, 'add_url': u'/admin/consommateurs/consommateurs/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommation/', 'object_name': 'consommation', 'name': <django.utils.functional.__proxy__ object at 0x7f54135918d0>, 'add_url': u'/admin/consommateurs/consommation/add/'}], 'has_module_perms': True, 'name': u'Consommateurs', 'app_label': u'consommateurs'}], u'LANGUAGE_CODE': 'fr-fr', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
(0.000) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = 1 ORDER BY "django_admin_log"."action_time" DESC LIMIT 10; args=(1,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-12 09:49:29.719351'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-12 09:49:29.719351')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) SELECT COUNT(*) AS "__count" FROM "auth_group"; args=()
(0.000) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" ORDER BY "auth_group"."name" ASC, "auth_group"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f54180a27d0>>}]"
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-12 09:49:30.221521'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-12 09:49:30.221521')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-12 09:49:32.325580'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-12 09:49:32.325580')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5413563ed8>>, 'user': <SimpleLazyObject: <User: admin>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5418058bd0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f541805f2d0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': <django.utils.functional.__proxy__ object at 0x7f5419d24590>, 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060950>, 'add_url': u'/admin/auth/group/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060c50>, 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x7f5419cad310>, 'app_label': 'auth'}, {'app_url': u'/admin/boissons/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/boissons/', 'object_name': 'boissons', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060b50>, 'add_url': u'/admin/boissons/boissons/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/stock/', 'object_name': 'Stock', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060e90>, 'add_url': u'/admin/boissons/stock/add/'}], 'has_module_perms': True, 'name': u'Boissons', 'app_label': u'boissons'}, {'app_url': u'/admin/consommateurs/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommateurs/', 'object_name': 'consommateurs', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060ad0>, 'add_url': u'/admin/consommateurs/consommateurs/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommation/', 'object_name': 'consommation', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060e10>, 'add_url': u'/admin/consommateurs/consommation/add/'}], 'has_module_perms': True, 'name': u'Consommateurs', 'app_label': u'consommateurs'}], 'site_title': <django.utils.functional.__proxy__ object at 0x7f5419d24550>, 'title': <django.utils.functional.__proxy__ object at 0x7f5419d245d0>, 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f990>, 'add_url': u'/admin/auth/group/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f1d0>, 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x7f5419cad310>, 'app_label': 'auth'}, {'app_url': u'/admin/boissons/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/boissons/', 'object_name': 'boissons', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f390>, 'add_url': u'/admin/boissons/boissons/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/stock/', 'object_name': 'Stock', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f610>, 'add_url': u'/admin/boissons/stock/add/'}], 'has_module_perms': True, 'name': u'Boissons', 'app_label': u'boissons'}, {'app_url': u'/admin/consommateurs/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommateurs/', 'object_name': 'consommateurs', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f310>, 'add_url': u'/admin/consommateurs/consommateurs/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommation/', 'object_name': 'consommation', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f690>, 'add_url': u'/admin/consommateurs/consommation/add/'}], 'has_module_perms': True, 'name': u'Consommateurs', 'app_label': u'consommateurs'}], u'LANGUAGE_CODE': 'fr-fr', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5413563ed8>>, 'user': <SimpleLazyObject: <User: admin>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5418058bd0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f541805f2d0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': <django.utils.functional.__proxy__ object at 0x7f5419d24590>, 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060950>, 'add_url': u'/admin/auth/group/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060c50>, 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x7f5419cad310>, 'app_label': 'auth'}, {'app_url': u'/admin/boissons/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/boissons/', 'object_name': 'boissons', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060b50>, 'add_url': u'/admin/boissons/boissons/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/stock/', 'object_name': 'Stock', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060e90>, 'add_url': u'/admin/boissons/stock/add/'}], 'has_module_perms': True, 'name': u'Boissons', 'app_label': u'boissons'}, {'app_url': u'/admin/consommateurs/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommateurs/', 'object_name': 'consommateurs', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060ad0>, 'add_url': u'/admin/consommateurs/consommateurs/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommation/', 'object_name': 'consommation', 'name': <django.utils.functional.__proxy__ object at 0x7f5418060e10>, 'add_url': u'/admin/consommateurs/consommation/add/'}], 'has_module_perms': True, 'name': u'Consommateurs', 'app_label': u'consommateurs'}], 'site_title': <django.utils.functional.__proxy__ object at 0x7f5419d24550>, 'title': <django.utils.functional.__proxy__ object at 0x7f5419d245d0>, 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f990>, 'add_url': u'/admin/auth/group/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f1d0>, 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x7f5419cad310>, 'app_label': 'auth'}, {'app_url': u'/admin/boissons/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/boissons/', 'object_name': 'boissons', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f390>, 'add_url': u'/admin/boissons/boissons/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/boissons/stock/', 'object_name': 'Stock', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f610>, 'add_url': u'/admin/boissons/stock/add/'}], 'has_module_perms': True, 'name': u'Boissons', 'app_label': u'boissons'}, {'app_url': u'/admin/consommateurs/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommateurs/', 'object_name': 'consommateurs', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f310>, 'add_url': u'/admin/consommateurs/consommateurs/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/consommateurs/consommation/', 'object_name': 'consommation', 'name': <django.utils.functional.__proxy__ object at 0x7f541805f690>, 'add_url': u'/admin/consommateurs/consommation/add/'}], 'has_module_perms': True, 'name': u'Consommateurs', 'app_label': u'consommateurs'}], u'LANGUAGE_CODE': 'fr-fr', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
(0.001) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = 1 ORDER BY "django_admin_log"."action_time" DESC LIMIT 10; args=(1,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-12 09:49:34.246883'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-12 09:49:34.246883')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group"; args=()
(0.001) SELECT COUNT(*) FROM (SELECT DISTINCT "auth_user"."id" AS Col1, "auth_user"."password" AS Col2, "auth_user"."last_login" AS Col3, "auth_user"."is_superuser" AS Col4, "auth_user"."username" AS Col5, "auth_user"."first_name" AS Col6, "auth_user"."last_name" AS Col7, "auth_user"."email" AS Col8, "auth_user"."is_staff" AS Col9, "auth_user"."is_active" AS Col10, "auth_user"."date_joined" AS Col11 FROM "auth_user") subquery; args=()
(0.000) SELECT DISTINCT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" ORDER BY "auth_user"."username" ASC, "auth_user"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5418097aa0>>}]"
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-12 09:49:34.487287'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-12 09:49:34.487287')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-12 09:50:00.047835'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-12 09:50:00.047835')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) BEGIN; args=None
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 3; args=(3,)
(0.000) SELECT "auth_group"."id" FROM "auth_group" INNER JOIN "auth_user_groups" ON ("auth_group"."id" = "auth_user_groups"."group_id") WHERE "auth_user_groups"."user_id" = 3; args=(3,)
(0.000) SELECT "auth_permission"."id" FROM "auth_permission" INNER JOIN "auth_user_user_permissions" ON ("auth_permission"."id" = "auth_user_user_permissions"."permission_id") INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_user_user_permissions"."user_id" = 3 ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(3,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'user' AND "django_content_type"."app_label" = 'auth'); args=('user', 'auth')
(0.000) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" ORDER BY "auth_group"."name" ASC; args=()
Exception while resolving variable 'can_change_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_change_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'widget\': u\'<select multiple="multiple" class="selectfilter" id="id_groups" name="groups">\\n</select><script type="text/javascript">addEvent(window, "load", function(e) {SelectFilter.init("id_groups", "groupes", 0); });</script>\\n\', \'add_related_url\': u\'/admin/auth/group/add/\', u\'name\': \'groups\', \'can_add_related\': True, u\'model\': <django.utils.functional.__proxy__ object at 0x7f54197244d0>, u\'url_params\': u\'_to_field=id&_popup=1\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n    \'>]>}]'
Exception while resolving variable 'can_delete_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'widget\': u\'<select multiple="multiple" class="selectfilter" id="id_groups" name="groups">\\n</select><script type="text/javascript">addEvent(window, "load", function(e) {SelectFilter.init("id_groups", "groupes", 0); });</script>\\n\', \'add_related_url\': u\'/admin/auth/group/add/\', u\'name\': \'groups\', \'can_add_related\': True, u\'model\': <django.utils.functional.__proxy__ object at 0x7f54197244d0>, u\'url_params\': u\'_to_field=id&_popup=1\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n    \'>]>}]'
(0.000) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=()
Exception while resolving variable 'can_change_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_change_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'model\': <django.utils.functional.__proxy__ object at 0x7f5419790d90>, u\'widget\': u\'<select multiple="multiple" class="selectfilter" id="id_user_permissions" name="user_permissions">\\n<option value="1">admin | entr\\xe9e d&#39;historique | Can add log entry</option>\\n<option value="2">admin | entr\\xe9e d&#39;historique | Can change log entry</option>\\n<option value="3">admin | entr\\xe9e d&#39;historique | Can delete log entry</option>\\n<option value="7">auth | groupe | Can add group</option>\\n<option value="8">auth | groupe | Can change group</option>\\n<option value="9">auth | groupe | Can delete group</option>\\n<option value="4">auth | permission | Can add permission</option>\\n<option value="5">auth | permission | Can change permission</option>\\n<option value="6">auth | permission | Can delete permission</option>\\n<option value="10">auth | utilisateur | Can add user</option>\\n<option value="11">auth | utilisateur | Can change user</option>\\n<option value="12">auth | utilisateur | Can delete user</option>\\n<option value="25">boissons | boissons | Can add boissons</option>\\n<option value="26">boissons | boissons | Can change boissons</option>\\n<option value="27">boissons | boissons | Can delete boissons</option>\\n<option value="28">boissons | stock | Can add stock</option>\\n<option value="29">boissons | stock | Can change stock</option>\\n<option value="30">boissons | stock | Can delete stock</option>\\n<option value="19">consommateurs | consommateurs | Can add consommateurs</option>\\n<option value="20">consommateurs | consommateurs | Can change consommateurs</option>\\n<option value="21">consommateurs | consommateurs | Can delete consommateurs</option>\\n<option value="22">consommateurs | consommation | Can add consommation</option>\\n<option value="23">consommateurs | consommation | Can change consommation</option>\\n<option value="24">consommateurs | consommation | Can delete consommation</option>\\n<option value="13">contenttypes | type de contenu | Can add content type</option>\\n<option value="14">contenttypes | type de contenu | Can change content type</option>\\n<option value="15">contenttypes | type de contenu | Can delete content type</option>\\n<option value="16">sessions | session | Can add session</option>\\n<option value="17">sessions | session | Can change session</option>\\n<option value="18">sessions | session | Can delete session</option>\\n</select><script type="text/javascript">addEvent(window, "load", function(e) {SelectFilter.init("id_user_permissions", "permissions de l\\\\u0027utilisateur", 0); });</script>\\n\', u\'name\': \'user_permissions\', u\'url_params\': u\'_to_field=id&_popup=1\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n    \'>]>}]'
Exception while resolving variable 'can_add_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_add_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'model\': <django.utils.functional.__proxy__ object at 0x7f5419790d90>, u\'widget\': u\'<select multiple="multiple" class="selectfilter" id="id_user_permissions" name="user_permissions">\\n<option value="1">admin | entr\\xe9e d&#39;historique | Can add log entry</option>\\n<option value="2">admin | entr\\xe9e d&#39;historique | Can change log entry</option>\\n<option value="3">admin | entr\\xe9e d&#39;historique | Can delete log entry</option>\\n<option value="7">auth | groupe | Can add group</option>\\n<option value="8">auth | groupe | Can change group</option>\\n<option value="9">auth | groupe | Can delete group</option>\\n<option value="4">auth | permission | Can add permission</option>\\n<option value="5">auth | permission | Can change permission</option>\\n<option value="6">auth | permission | Can delete permission</option>\\n<option value="10">auth | utilisateur | Can add user</option>\\n<option value="11">auth | utilisateur | Can change user</option>\\n<option value="12">auth | utilisateur | Can delete user</option>\\n<option value="25">boissons | boissons | Can add boissons</option>\\n<option value="26">boissons | boissons | Can change boissons</option>\\n<option value="27">boissons | boissons | Can delete boissons</option>\\n<option value="28">boissons | stock | Can add stock</option>\\n<option value="29">boissons | stock | Can change stock</option>\\n<option value="30">boissons | stock | Can delete stock</option>\\n<option value="19">consommateurs | consommateurs | Can add consommateurs</option>\\n<option value="20">consommateurs | consommateurs | Can change consommateurs</option>\\n<option value="21">consommateurs | consommateurs | Can delete consommateurs</option>\\n<option value="22">consommateurs | consommation | Can add consommation</option>\\n<option value="23">consommateurs | consommation | Can change consommation</option>\\n<option value="24">consommateurs | consommation | Can delete consommation</option>\\n<option value="13">contenttypes | type de contenu | Can add content type</option>\\n<option value="14">contenttypes | type de contenu | Can change content type</option>\\n<option value="15">contenttypes | type de contenu | Can delete content type</option>\\n<option value="16">sessions | session | Can add session</option>\\n<option value="17">sessions | session | Can change session</option>\\n<option value="18">sessions | session | Can delete session</option>\\n</select><script type="text/javascript">addEvent(window, "load", function(e) {SelectFilter.init("id_user_permissions", "permissions de l\\\\u0027utilisateur", 0); });</script>\\n\', u\'name\': \'user_permissions\', u\'url_params\': u\'_to_field=id&_popup=1\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n    \'>]>}]'
Exception while resolving variable 'can_delete_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'model\': <django.utils.functional.__proxy__ object at 0x7f5419790d90>, u\'widget\': u\'<select multiple="multiple" class="selectfilter" id="id_user_permissions" name="user_permissions">\\n<option value="1">admin | entr\\xe9e d&#39;historique | Can add log entry</option>\\n<option value="2">admin | entr\\xe9e d&#39;historique | Can change log entry</option>\\n<option value="3">admin | entr\\xe9e d&#39;historique | Can delete log entry</option>\\n<option value="7">auth | groupe | Can add group</option>\\n<option value="8">auth | groupe | Can change group</option>\\n<option value="9">auth | groupe | Can delete group</option>\\n<option value="4">auth | permission | Can add permission</option>\\n<option value="5">auth | permission | Can change permission</option>\\n<option value="6">auth | permission | Can delete permission</option>\\n<option value="10">auth | utilisateur | Can add user</option>\\n<option value="11">auth | utilisateur | Can change user</option>\\n<option value="12">auth | utilisateur | Can delete user</option>\\n<option value="25">boissons | boissons | Can add boissons</option>\\n<option value="26">boissons | boissons | Can change boissons</option>\\n<option value="27">boissons | boissons | Can delete boissons</option>\\n<option value="28">boissons | stock | Can add stock</option>\\n<option value="29">boissons | stock | Can change stock</option>\\n<option value="30">boissons | stock | Can delete stock</option>\\n<option value="19">consommateurs | consommateurs | Can add consommateurs</option>\\n<option value="20">consommateurs | consommateurs | Can change consommateurs</option>\\n<option value="21">consommateurs | consommateurs | Can delete consommateurs</option>\\n<option value="22">consommateurs | consommation | Can add consommation</option>\\n<option value="23">consommateurs | consommation | Can change consommation</option>\\n<option value="24">consommateurs | consommation | Can delete consommation</option>\\n<option value="13">contenttypes | type de contenu | Can add content type</option>\\n<option value="14">contenttypes | type de contenu | Can change content type</option>\\n<option value="15">contenttypes | type de contenu | Can delete content type</option>\\n<option value="16">sessions | session | Can add session</option>\\n<option value="17">sessions | session | Can change session</option>\\n<option value="18">sessions | session | Can delete session</option>\\n</select><script type="text/javascript">addEvent(window, "load", function(e) {SelectFilter.init("id_user_permissions", "permissions de l\\\\u0027utilisateur", 0); });</script>\\n\', u\'name\': \'user_permissions\', u\'url_params\': u\'_to_field=id&_popup=1\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n    \'>]>}]'
(0.006) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-12 09:50:00.594092'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-12 09:50:00.594092')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-12 09:50:08.558039'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-12 09:50:08.558039')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group"; args=()
(0.000) SELECT COUNT(*) FROM (SELECT DISTINCT "auth_user"."id" AS Col1, "auth_user"."password" AS Col2, "auth_user"."last_login" AS Col3, "auth_user"."is_superuser" AS Col4, "auth_user"."username" AS Col5, "auth_user"."first_name" AS Col6, "auth_user"."last_name" AS Col7, "auth_user"."email" AS Col8, "auth_user"."is_staff" AS Col9, "auth_user"."is_active" AS Col10, "auth_user"."date_joined" AS Col11 FROM "auth_user") subquery; args=()
(0.000) SELECT DISTINCT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" ORDER BY "auth_user"."username" ASC, "auth_user"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5413557578>>}]"
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-12 09:50:10.780420'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-12 09:50:10.780420')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) BEGIN; args=None
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 5; args=(5,)
(0.000) SELECT "auth_group"."id" FROM "auth_group" INNER JOIN "auth_user_groups" ON ("auth_group"."id" = "auth_user_groups"."group_id") WHERE "auth_user_groups"."user_id" = 5; args=(5,)
(0.000) SELECT "auth_permission"."id" FROM "auth_permission" INNER JOIN "auth_user_user_permissions" ON ("auth_permission"."id" = "auth_user_user_permissions"."permission_id") INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_user_user_permissions"."user_id" = 5 ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(5,)
(0.000) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" ORDER BY "auth_group"."name" ASC; args=()
Exception while resolving variable 'can_change_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_change_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'widget\': u\'<select multiple="multiple" class="selectfilter" id="id_groups" name="groups">\\n</select><script type="text/javascript">addEvent(window, "load", function(e) {SelectFilter.init("id_groups", "groupes", 0); });</script>\\n\', \'add_related_url\': u\'/admin/auth/group/add/\', u\'name\': \'groups\', \'can_add_related\': True, u\'model\': <django.utils.functional.__proxy__ object at 0x7f54197244d0>, u\'url_params\': u\'_to_field=id&_popup=1\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n    \'>]>}]'
Exception while resolving variable 'can_delete_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'widget\': u\'<select multiple="multiple" class="selectfilter" id="id_groups" name="groups">\\n</select><script type="text/javascript">addEvent(window, "load", function(e) {SelectFilter.init("id_groups", "groupes", 0); });</script>\\n\', \'add_related_url\': u\'/admin/auth/group/add/\', u\'name\': \'groups\', \'can_add_related\': True, u\'model\': <django.utils.functional.__proxy__ object at 0x7f54197244d0>, u\'url_params\': u\'_to_field=id&_popup=1\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n    \'>]>}]'
(0.000) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=()
Exception while resolving variable 'can_change_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_change_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'model\': <django.utils.functional.__proxy__ object at 0x7f5419790d90>, u\'widget\': u\'<select multiple="multiple" class="selectfilter" id="id_user_permissions" name="user_permissions">\\n<option value="1">admin | entr\\xe9e d&#39;historique | Can add log entry</option>\\n<option value="2">admin | entr\\xe9e d&#39;historique | Can change log entry</option>\\n<option value="3">admin | entr\\xe9e d&#39;historique | Can delete log entry</option>\\n<option value="7">auth | groupe | Can add group</option>\\n<option value="8">auth | groupe | Can change group</option>\\n<option value="9">auth | groupe | Can delete group</option>\\n<option value="4">auth | permission | Can add permission</option>\\n<option value="5">auth | permission | Can change permission</option>\\n<option value="6">auth | permission | Can delete permission</option>\\n<option value="10">auth | utilisateur | Can add user</option>\\n<option value="11">auth | utilisateur | Can change user</option>\\n<option value="12">auth | utilisateur | Can delete user</option>\\n<option value="25">boissons | boissons | Can add boissons</option>\\n<option value="26">boissons | boissons | Can change boissons</option>\\n<option value="27">boissons | boissons | Can delete boissons</option>\\n<option value="28">boissons | stock | Can add stock</option>\\n<option value="29">boissons | stock | Can change stock</option>\\n<option value="30">boissons | stock | Can delete stock</option>\\n<option value="19">consommateurs | consommateurs | Can add consommateurs</option>\\n<option value="20">consommateurs | consommateurs | Can change consommateurs</option>\\n<option value="21">consommateurs | consommateurs | Can delete consommateurs</option>\\n<option value="22">consommateurs | consommation | Can add consommation</option>\\n<option value="23">consommateurs | consommation | Can change consommation</option>\\n<option value="24">consommateurs | consommation | Can delete consommation</option>\\n<option value="13">contenttypes | type de contenu | Can add content type</option>\\n<option value="14">contenttypes | type de contenu | Can change content type</option>\\n<option value="15">contenttypes | type de contenu | Can delete content type</option>\\n<option value="16">sessions | session | Can add session</option>\\n<option value="17">sessions | session | Can change session</option>\\n<option value="18">sessions | session | Can delete session</option>\\n</select><script type="text/javascript">addEvent(window, "load", function(e) {SelectFilter.init("id_user_permissions", "permissions de l\\\\u0027utilisateur", 0); });</script>\\n\', u\'name\': \'user_permissions\', u\'url_params\': u\'_to_field=id&_popup=1\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n    \'>]>}]'
Exception while resolving variable 'can_add_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_add_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'model\': <django.utils.functional.__proxy__ object at 0x7f5419790d90>, u\'widget\': u\'<select multiple="multiple" class="selectfilter" id="id_user_permissions" name="user_permissions">\\n<option value="1">admin | entr\\xe9e d&#39;historique | Can add log entry</option>\\n<option value="2">admin | entr\\xe9e d&#39;historique | Can change log entry</option>\\n<option value="3">admin | entr\\xe9e d&#39;historique | Can delete log entry</option>\\n<option value="7">auth | groupe | Can add group</option>\\n<option value="8">auth | groupe | Can change group</option>\\n<option value="9">auth | groupe | Can delete group</option>\\n<option value="4">auth | permission | Can add permission</option>\\n<option value="5">auth | permission | Can change permission</option>\\n<option value="6">auth | permission | Can delete permission</option>\\n<option value="10">auth | utilisateur | Can add user</option>\\n<option value="11">auth | utilisateur | Can change user</option>\\n<option value="12">auth | utilisateur | Can delete user</option>\\n<option value="25">boissons | boissons | Can add boissons</option>\\n<option value="26">boissons | boissons | Can change boissons</option>\\n<option value="27">boissons | boissons | Can delete boissons</option>\\n<option value="28">boissons | stock | Can add stock</option>\\n<option value="29">boissons | stock | Can change stock</option>\\n<option value="30">boissons | stock | Can delete stock</option>\\n<option value="19">consommateurs | consommateurs | Can add consommateurs</option>\\n<option value="20">consommateurs | consommateurs | Can change consommateurs</option>\\n<option value="21">consommateurs | consommateurs | Can delete consommateurs</option>\\n<option value="22">consommateurs | consommation | Can add consommation</option>\\n<option value="23">consommateurs | consommation | Can change consommation</option>\\n<option value="24">consommateurs | consommation | Can delete consommation</option>\\n<option value="13">contenttypes | type de contenu | Can add content type</option>\\n<option value="14">contenttypes | type de contenu | Can change content type</option>\\n<option value="15">contenttypes | type de contenu | Can delete content type</option>\\n<option value="16">sessions | session | Can add session</option>\\n<option value="17">sessions | session | Can change session</option>\\n<option value="18">sessions | session | Can delete session</option>\\n</select><script type="text/javascript">addEvent(window, "load", function(e) {SelectFilter.init("id_user_permissions", "permissions de l\\\\u0027utilisateur", 0); });</script>\\n\', u\'name\': \'user_permissions\', u\'url_params\': u\'_to_field=id&_popup=1\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n    \'>]>}]'
Exception while resolving variable 'can_delete_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'model\': <django.utils.functional.__proxy__ object at 0x7f5419790d90>, u\'widget\': u\'<select multiple="multiple" class="selectfilter" id="id_user_permissions" name="user_permissions">\\n<option value="1">admin | entr\\xe9e d&#39;historique | Can add log entry</option>\\n<option value="2">admin | entr\\xe9e d&#39;historique | Can change log entry</option>\\n<option value="3">admin | entr\\xe9e d&#39;historique | Can delete log entry</option>\\n<option value="7">auth | groupe | Can add group</option>\\n<option value="8">auth | groupe | Can change group</option>\\n<option value="9">auth | groupe | Can delete group</option>\\n<option value="4">auth | permission | Can add permission</option>\\n<option value="5">auth | permission | Can change permission</option>\\n<option value="6">auth | permission | Can delete permission</option>\\n<option value="10">auth | utilisateur | Can add user</option>\\n<option value="11">auth | utilisateur | Can change user</option>\\n<option value="12">auth | utilisateur | Can delete user</option>\\n<option value="25">boissons | boissons | Can add boissons</option>\\n<option value="26">boissons | boissons | Can change boissons</option>\\n<option value="27">boissons | boissons | Can delete boissons</option>\\n<option value="28">boissons | stock | Can add stock</option>\\n<option value="29">boissons | stock | Can change stock</option>\\n<option value="30">boissons | stock | Can delete stock</option>\\n<option value="19">consommateurs | consommateurs | Can add consommateurs</option>\\n<option value="20">consommateurs | consommateurs | Can change consommateurs</option>\\n<option value="21">consommateurs | consommateurs | Can delete consommateurs</option>\\n<option value="22">consommateurs | consommation | Can add consommation</option>\\n<option value="23">consommateurs | consommation | Can change consommation</option>\\n<option value="24">consommateurs | consommation | Can delete consommation</option>\\n<option value="13">contenttypes | type de contenu | Can add content type</option>\\n<option value="14">contenttypes | type de contenu | Can change content type</option>\\n<option value="15">contenttypes | type de contenu | Can delete content type</option>\\n<option value="16">sessions | session | Can add session</option>\\n<option value="17">sessions | session | Can change session</option>\\n<option value="18">sessions | session | Can delete session</option>\\n</select><script type="text/javascript">addEvent(window, "load", function(e) {SelectFilter.init("id_user_permissions", "permissions de l\\\\u0027utilisateur", 0); });</script>\\n\', u\'name\': \'user_permissions\', u\'url_params\': u\'_to_field=id&_popup=1\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n        \'>, <IfNode>, <TextNode: u\'\\n    \'>]>}]'
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'xp9ygb1qsodtgyz6m286l1asdi17y3zf' AND "django_session"."expire_date" > '2016-01-12 09:50:11.239923'); args=('xp9ygb1qsodtgyz6m286l1asdi17y3zf', u'2016-01-12 09:50:11.239923')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Not Found: //static/registration/style.css
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'registration.backends.hmac.urls' from '/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/urls.pyc'> (None:None) ^accounts/>"
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Not Found: //static/registration/style.css
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'registration.backends.hmac.urls' from '/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/urls.pyc'> (None:None) ^accounts/>"
Not Found: /accounts/register/consommateurs/static/registration/style.css
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Not Found: /consommateurs/static/registration/style.css
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'registration.backends.hmac.urls' from '/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/urls.pyc'> (None:None) ^accounts/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'registration.backends.hmac.urls' from '/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/urls.pyc'> (None:None) ^accounts/>"
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Not Found: /accounts/
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Not Found: /boissons
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'registration.backends.hmac.urls' from '/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/urls.pyc'> (None:None) ^accounts/>"
Not Found: /accounts
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'registration.backends.hmac.urls' from '/usr/local/lib/python2.7/dist-packages/registration/backends/hmac/urls.pyc'> (None:None) ^accounts/>"
Not Found: /accounts/
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'boissons.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/boissons/urls.pyc'> (None:None) ^boissons/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'consommateurs.urls' from '/home/jerome/Sources/GestionBoissons/GestionBoissonDj/gestionboisson/consommateurs/urls.pyc'> (None:None) ^consommateurs/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
